sudo: false
matrix:
    fast_finish: true
    include:
        - python: "3.4"
        - python: "3.5"
        - python: "3.6"
        - python: "3.6-dev"
        - python: "3.7-dev"
cache:
    directories:
        - $HOME/.cache/pip
install:
    - pip install -U coveralls pytest
language: python
script:
    - coverage run -m pytest
after_success:
    - coveralls
